
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - conference.example.org
  resources:
  - talks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - conference.example.org
  resources:
  - talks/finalizers
  verbs:
  - update
- apiGroups:
  - conference.example.org
  resources:
  - talks/status
  verbs:
  - get
  - patch
  - update
