# permissions for end users to view talks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: talk-viewer-role
rules:
- apiGroups:
  - conference.example.org
  resources:
  - talks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - conference.example.org
  resources:
  - talks/status
  verbs:
  - get
